name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy frontend to docs
        run: |
          mkdir -p docs
          cp -r frontend/* docs/
          # Оновлюємо URL бекенду
          sed -i 's|http://localhost:5000|https://smart-ratecon.onrender.com|g' docs/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
